# opdracht 1 en 2 van paragraaf 2.7
voornaam = input ("wat is je voornaam")
achternaam = input ("wat is je achternaam")
print("hallo" + voornaam + " " + achternaam + "!") 
naam = input("Wat is je naam?")
straat = input("In welke straat woon je?")
huisnummer = input("Wat is je huisnummer?")
postcode = input("Wat is je postcode?")
woonplaats = input("Wat is je woonplaats?")
print(naam)
print(straat + " " + huisnummer)
print(postcode.upper() + "  " + woonplaats.upper())